const { BASELINE } = require('../config/baseline');
const { SERVICES } = require('../config/services');

function escapeHtml(str) {
    if (str == null) return '';
    return String(str)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
}

const STATUS_LABELS = {
    to_do: 'To Do',
    in_progress: 'In Progress',
    completed: 'Completed',
    on_hold_client: 'On Hold - Client',
    on_hold_internal: 'On Hold - Internal',
};

const STATUS_ORDER = ['on_hold_client', 'in_progress', 'to_do', 'on_hold_internal', 'completed'];

function renderDashboard(tasks, key) {
    key = key || '';
    const counts = {};
    for (const s of STATUS_ORDER) counts[s] = 0;
    for (const t of tasks) counts[t.status] = (counts[t.status] || 0) + 1;

  const complianceWatch = tasks.filter(
        (t) => t.status === 'on_hold_client' && !t.blocker_note
      );

  const groupedByStatus = STATUS_ORDER.map((status) => ({
        status,
        label: STATUS_LABELS[status],
        tasks: tasks.filter((t) => t.status === status),
  }));

  const groupedByWorkstream = [...SERVICES, 'Operations'].map((ws) => ({
        workstream: ws,
        tasks: tasks.filter((t) => t.workstream === ws),
  }));

  const workstreamOptions = [...SERVICES, 'Operations']
      .map((ws) => `<option value="${escapeHtml(ws)}">${escapeHtml(ws)}</option>`)
      .join('');

  const countCards = STATUS_ORDER.map(
        (s) => `<div class="count-card"><div class="count-num">${counts[s]}</div><div class="count-label">${STATUS_LABELS[s]}</div></div>`
      ).join('');

  const statusOptionsFor = (current) =>
        STATUS_ORDER.map(
                (s) => `<option value="${s}"${s === current ? ' selected' : ''}>${STATUS_LABELS[s]}</option>`
              ).join('');

  const statusSections = groupedByStatus
      .map(
              (group) => `
                  <section class="status-group">
                        <h3>${group.label} <span class="badge">${group.tasks.length}</span></h3>
                              ${
                                        group.tasks.length === 0
                                          ? '<p class="empty">None</p>'
                                          : `<div class="table-scroll"><table>
                                                  <thead><tr><th>Title</th><th>Workstream</th><th>Assignee</th><th>Internal Blocked</th><th>Blocker Note</th><th>Origin</th><th>Status</th></tr></thead>
                                                          <tbody>
                                                                  ${group.tasks
                                                                              .map(
                                                                                            (t) => `<tr>
                                                                                                      <td>${escapeHtml(t.title)}</td>
                                                                                                                <td>${escapeHtml(t.workstream)}</td>
                                                                                                                          <td${t.assignee ? '' : ' class="unassigned"'}>${escapeHtml(t.assignee) || 'Unassigned'}</td>
                                                                                                                                    <td>${t.internal_blocked ? 'Yes' : 'No'}</td>
                                                                                                                                              <td>${escapeHtml(t.blocker_note) || ''}</td>
                                                                                                                                                        <td class="origin">${escapeHtml(t.origin)}${t.external_ref ? ` (${escapeHtml(t.external_ref)})` : ''}</td>
                                                                                                                                                                  <td><select class="status-select" data-task-id="${t.id}">${statusOptionsFor(t.status)}</select></td>
                                                                                                                                                                          </tr>`
                                                                                          )
                                                                              .join('')}
                                                                                      </tbody>
                                                                                            </table></div>`
                              }
                                  </section>`
            )
      .join('');

  const workstreamSummary = groupedByWorkstream
      .map(
              (g) => `<div class="ws-card"><div class="ws-label">${escapeHtml(g.workstream)}</div><div class="ws-count">${g.tasks.length} tasks</div></div>`
            )
      .join('');

  return `<!DOCTYPE html>
  <html>
  <head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>NYFG Weekly Update Agent - Internal Dashboard</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,400;0,500;0,600;1,400;1,500&family=Jost:wght@300;400;500;600&display=swap" rel="stylesheet">
  <style>
    * { box-sizing: border-box; }
      body { margin: 0; font-family: 'Jost', sans-serif; background: #F7F1E3; color: #2A2420; padding: 56px 64px 96px; }
        ::selection { background: #C2A05F; color: #FFFFFF; }
          .header { display: flex; align-items: flex-end; justify-content: space-between; gap: 24px; padding-bottom: 28px; border-bottom: 1px solid #E6DAC0; margin-bottom: 40px; flex-wrap: wrap; }
            .brand { display: flex; align-items: center; gap: 20px; }
              .logo-mark { width: 64px; height: 64px; flex-shrink: 0; border-radius: 4px; background: #2A2118; color: #D8B968; display: flex; align-items: center; justify-content: center; font-family: 'Cormorant Garamond', serif; font-size: 20px; letter-spacing: 0.05em; }
                .brand-name { font-family: 'Cormorant Garamond', serif; font-size: 30px; letter-spacing: 0.04em; line-height: 1.1; }
                  .brand-sub { font-size: 11px; letter-spacing: 0.14em; text-transform: uppercase; color: #9C8B70; margin-top: 6px; }
                    .internal-badge { padding: 9px 18px; border: 1px solid #C2A05F; color: #8A6F35; font-size: 10.5px; letter-spacing: 0.12em; text-transform: uppercase; border-radius: 3px; }
                      .baseline-card { background: #2A2118; color: #F3ECDD; padding: 28px 32px; border-radius: 4px; margin-bottom: 32px; }
                        .baseline-label { font-size: 11px; letter-spacing: 0.1em; text-transform: uppercase; color: #C9BBA0; margin-bottom: 10px; }
                          .baseline-score { font-family: 'Cormorant Garamond', serif; font-size: 44px; color: #D8B968; display: flex; align-items: baseline; gap: 14px; }
                            .baseline-score span { font-family: 'Jost', sans-serif; font-size: 15px; color: #C9BBA0; font-weight: 300; }
                              .baseline-note { font-size: 12px; color: #A8987C; margin-top: 8px; }
                                .compliance-watch { background: #FBF0E4; border: 1px solid #E8C89A; border-radius: 4px; padding: 14px 18px; margin-bottom: 24px; font-size: 13px; color: #6B4A26; line-height: 1.6; }
                                  .counts-row { display: flex; gap: 14px; margin-bottom: 36px; flex-wrap: wrap; }
                                    .count-card { background: #FFFFFF; border: 1px solid #E6DAC0; border-radius: 4px; padding: 16px 24px; text-align: center; min-width: 120px; }
                                      .count-num { font-family: 'Cormorant Garamond', serif; font-size: 30px; color: #C2A05F; }
                                        .count-label { font-size: 10.5px; letter-spacing: 0.08em; text-transform: uppercase; color: #9C8B70; margin-top: 4px; }
                                          .panel { background: #FFFFFF; border: 1px solid #E6DAC0; border-radius: 4px; padding: 28px 32px; margin-bottom: 24px; }
                                            .panel h2 { font-family: 'Cormorant Garamond', serif; font-size: 24px; margin: 0 0 16px; font-weight: 500; }
                                              .panel p.desc { font-size: 13px; color: #8A7A63; margin: 0 0 16px; line-height: 1.6; max-width: 620px; }
                                                .add-task-form { display: flex; gap: 10px; flex-wrap: wrap; align-items: center; }
                                                  .add-task-form input, .add-task-form select { padding: 9px 12px; border: 1px solid #DCCFAF; border-radius: 3px; font-size: 13px; font-family: 'Jost', sans-serif; color: #2A2420; background: #FDFBF4; }
                                                    .add-task-form input::placeholder { color: #B3A688; opacity: 1; }
                                                      .btn-dark { background: #2A2118; color: #F3ECDD; border: none; border-radius: 3px; padding: 10px 22px; font-size: 11.5px; letter-spacing: 0.08em; text-transform: uppercase; cursor: pointer; font-family: 'Jost', sans-serif; }
                                                        .form-status { margin-top: 12px; font-size: 13px; color: #8A6F35; }
                                                          .draft-box { background: #FBF6EA; border: 1px solid #E6DAC0; border-radius: 4px; padding: 16px 20px; margin-top: 14px; font-size: 13px; color: #3A3128; white-space: pre-wrap; line-height: 1.6; }
                                                            .draft-refused { background: #FBF0E4; border: 1px solid #E8C89A; border-radius: 4px; padding: 14px 18px; margin-top: 14px; font-size: 13px; color: #6B4A26; line-height: 1.6; }
                                                              .draft-error { background: #FBEBE8; border: 1px solid #E3B3AC; border-radius: 4px; padding: 14px 18px; margin-top: 14px; font-size: 13px; color: #8A3A2E; }
                                                                h2.section-title { font-family: 'Cormorant Garamond', serif; font-size: 26px; margin-bottom: 16px; font-weight: 500; }
                                                                  .ws-row { display: flex; gap: 14px; margin-bottom: 36px; flex-wrap: wrap; }
                                                                    .ws-card { background: #FFFFFF; border: 1px solid #E6DAC0; border-radius: 4px; padding: 14px 22px; }
                                                                      .ws-label { font-size: 13.5px; margin-bottom: 4px; }
                                                                        .ws-count { font-size: 11.5px; color: #9C8B70; }
                                                                          .status-group { background: #FFFFFF; border: 1px solid #E6DAC0; border-radius: 4px; padding: 22px 26px; margin-bottom: 18px; }
                                                                            .status-group h3 { margin: 0 0 14px; font-family: 'Cormorant Garamond', serif; font-size: 20px; font-weight: 500; display: flex; align-items: center; gap: 10px; }
                                                                              .badge { background: #C2A05F; color: #FFFFFF; border-radius: 999px; padding: 2px 12px; font-size: 12px; font-family: 'Jost', sans-serif; }
                                                                                .empty { color: #B3A688; font-style: italic; font-size: 13px; margin: 8px 0 0; }
                                                                                  .table-scroll { overflow-x: auto; }
                                                                                    table { width: 100%; border-collapse: collapse; }
                                                                                      th { padding: 10px 14px; text-align: left; border-bottom: 1px solid #E6DAC0; font-size: 10px; letter-spacing: .09em; text-transform: uppercase; color: #9C8B70; font-weight: 500; }
                                                                                        td { padding: 10px 14px; border-bottom: 1px solid #F0E9D8; font-size: 13px; }
                                                                                          td.origin { font-size: 12.5px; color: #9C8B70; }
                                                                                            td.unassigned { font-style: italic; color: #B3A688; }
                                                                                              .status-select { padding: 6px 10px; border: 1px solid #DCCFAF; border-radius: 3px; font-size: 12px; font-family: 'Jost', sans-serif; color: #2A2420; background: #FDFBF4; }
                                                                                              </style>
                                                                                              </head>
                                                                                              <body>
                                                                                                <div class="header">
                                                                                                    <div class="brand">
                                                                                                          <div class="logo-mark">NYFG</div>
                                                                                                                <div>
                                                                                                                        <div class="brand-name">New York Flower Group</div>
                                                                                                                                <div class="brand-sub">Weekly Update Agent</div>
                                                                                                                                      </div>
                                                                                                                                          </div>
                                                                                                                                              <div class="internal-badge">Internal &middot; Not for client viewing</div>
                                                                                                                                                </div>
                                                                                                                                                
                                                                                                                                                  <div class="baseline-card">
                                                                                                                                                      <div class="baseline-label">${escapeHtml(BASELINE.label)}</div>
                                                                                                                                                          <div class="baseline-score">${BASELINE.current} / ${BASELINE.scale} <span>&rarr; target ${BASELINE.target}</span></div>
                                                                                                                                                              <div class="baseline-note">${escapeHtml(BASELINE.guaranteeNote)} &middot; last verified ${escapeHtml(BASELINE.lastVerified)}</div>
                                                                                                                                                                </div>
                                                                                                                                                                
                                                                                                                                                                  ${
                                                                                                                                                                        complianceWatch.length > 0
                                                                                                                                                                          ? `<div class="compliance-watch">${complianceWatch.length} task(s) marked On Hold - Client with no blocker note recorded. Review before the next client draft.</div>`
                                                                                                                                                                          : ''
                                                                                                                                                                    }
                                                                                                                                                                    
                                                                                                                                                                      <div class="counts-row">${countCards}</div>
                                                                                                                                                                      
                                                                                                                                                                        <div class="panel">
                                                                                                                                                                            <h2>Add Task</h2>
                                                                                                                                                                                <form id="add-task-form" class="add-task-form">
                                                                                                                                                                                      <input type="text" id="task-title" placeholder="Task title" required>
                                                                                                                                                                                            <select id="task-workstream" required>
                                                                                                                                                                                                    <option value="">Workstream&hellip;</option>
                                                                                                                                                                                                            ${workstreamOptions}
                                                                                                                                                                                                                  </select>
                                                                                                                                                                                                                        <select id="task-type">
                                                                                                                                                                                                                                <option value="one_shot">One-shot</option>
                                                                                                                                                                                                                                        <option value="recurring">Recurring</option>
                                                                                                                                                                                                                                              </select>
                                                                                                                                                                                                                                                    <input type="text" id="task-cadence" placeholder="Cadence (recurring only)">
                                                                                                                                                                                                                                                          <input type="text" id="task-assignee" placeholder="Assignee (optional)">
                                                                                                                                                                                                                                                                <button type="submit" class="btn-dark">Add Task</button>
                                                                                                                                                                                                                                                                    </form>
                                                                                                                                                                                                                                                                        <div id="add-task-status" class="form-status"></div>
                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                            <div class="panel">
                                                                                                                                                                                                                                                                                <h2>Client Draft</h2>
                                                                                                                                                                                                                                                                                    <p class="desc">Generates a redacted draft for Jay to review. This never sends anything to the client &mdash; a human must copy, review, and send it.</p>
                                                                                                                                                                                                                                                                                        <button id="generate-draft-btn" type="button" class="btn-dark">Generate Client Draft</button>
                                                                                                                                                                                                                                                                                            <div id="draft-output"></div>
                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                <h2 class="section-title">By Service Pillar</h2>
                                                                                                                                                                                                                                                                                                  <div class="ws-row">${workstreamSummary}</div>
                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                    <h2 class="section-title">By Status</h2>
                                                                                                                                                                                                                                                                                                      ${statusSections}
                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                      <script>
                                                                                                                                                                                                                                                                                                      (function () {
                                                                                                                                                                                                                                                                                                        var API_KEY = ${JSON.stringify(key)};
                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                          function escapeClient(str) {
                                                                                                                                                                                                                                                                                                              if (str === undefined || str === null) return '';
                                                                                                                                                                                                                                                                                                                  var div = document.createElement('div');
                                                                                                                                                                                                                                                                                                                      div.innerText = typeof str === 'string' ? str : JSON.stringify(str);
                                                                                                                                                                                                                                                                                                                          return div.innerHTML;
                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                              var taskTypeEl = document.getElementById('task-type');
                                                                                                                                                                                                                                                                                                                                var cadenceEl = document.getElementById('task-cadence');
                                                                                                                                                                                                                                                                                                                                  taskTypeEl.addEventListener('change', function () {
                                                                                                                                                                                                                                                                                                                                      cadenceEl.style.display = taskTypeEl.value === 'recurring' ? 'inline-block' : 'none';
                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                          cadenceEl.style.display = 'none';
                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                            document.getElementById('add-task-form').addEventListener('submit', function (e) {
                                                                                                                                                                                                                                                                                                                                                e.preventDefault();
                                                                                                                                                                                                                                                                                                                                                    var statusEl = document.getElementById('add-task-status');
                                                                                                                                                                                                                                                                                                                                                        statusEl.textContent = 'Adding...';
                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                            var type = taskTypeEl.value;
                                                                                                                                                                                                                                                                                                                                                                var body = {
                                                                                                                                                                                                                                                                                                                                                                      title: document.getElementById('task-title').value,
                                                                                                                                                                                                                                                                                                                                                                            origin: 'dashboard',
                                                                                                                                                                                                                                                                                                                                                                                  workstream: document.getElementById('task-workstream').value,
                                                                                                                                                                                                                                                                                                                                                                                        task_type: type,
                                                                                                                                                                                                                                                                                                                                                                                              assignee: document.getElementById('task-assignee').value || undefined,
                                                                                                                                                                                                                                                                                                                                                                                                  };
                                                                                                                                                                                                                                                                                                                                                                                                      if (type === 'recurring') {
                                                                                                                                                                                                                                                                                                                                                                                                            body.cadence = cadenceEl.value;
                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                    fetch('/tasks', {
                                                                                                                                                                                                                                                                                                                                                                                                                          method: 'POST',
                                                                                                                                                                                                                                                                                                                                                                                                                                headers: { 'Content-Type': 'application/json', 'X-API-Key': API_KEY },
                                                                                                                                                                                                                                                                                                                                                                                                                                      body: JSON.stringify(body),
                                                                                                                                                                                                                                                                                                                                                                                                                                          })
                                                                                                                                                                                                                                                                                                                                                                                                                                                .then(function (res) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        return res.json().then(function (data) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return { ok: res.ok, data: data };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      .then(function (result) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (!result.ok) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        statusEl.textContent = 'Error: ' + (result.data.error || 'request failed');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          statusEl.textContent = 'Added task #' + result.data.id + '. Reload the page to see it grouped.';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    document.getElementById('add-task-form').reset();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              cadenceEl.style.display = 'none';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  .catch(function (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          statusEl.textContent = 'Request failed: ' + err.message;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    document.getElementById('generate-draft-btn').addEventListener('click', function () {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        var out = document.getElementById('draft-output');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            out.innerHTML = '<div class="form-status">Generating...</div>';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fetch('/client-draft', {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      method: 'POST',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            headers: { 'X-API-Key': API_KEY },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      .then(function (res) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return res.json().then(function (data) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return { status: res.status, ok: res.ok, data: data };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .then(function (result) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (result.status === 409) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              out.innerHTML =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          '<div class="draft-refused"><strong>Refused:</strong> ' +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      escapeClient(result.data.reason) +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  '<br>Violations: ' +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              escapeClient(JSON.stringify(result.data.violations)) +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          '</div>';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  } else if (!result.ok) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            out.innerHTML = '<div class="draft-error">Error: ' + escapeClient(result.data.error || result.status) + '</div>';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              out.innerHTML =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          '<div class="draft-box"><strong>DRAFT ONLY &mdash; route to ' +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      escapeClient(result.data.approver) +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ' for approval. A human must send this.</strong><br><br>' +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              escapeClient(result.data.draft) +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          '</div>';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              .catch(function (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      out.innerHTML = '<div class="draft-error">Request failed: ' + escapeClient(err.message) + '</div>';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                document.querySelectorAll('.status-select').forEach(function (sel) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    sel.addEventListener('change', function () {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          var id = sel.getAttribute('data-task-id');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fetch('/tasks/' + id + '/status', {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        method: 'POST',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                headers: { 'Content-Type': 'application/json', 'X-API-Key': API_KEY },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        body: JSON.stringify({ status: sel.value }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }).catch(function () {});
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    })();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </script>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </html>`;
}

module.exports = { renderDashboard };
