-- Seed data for NYFG Weekly Update Agent
-- Generated from live ClickUp pull (folder 90169623534, lists 901614956007 + 901614956006)
-- plus 3 Jay-confirmed project-origin tasks from Claude project history.
-- Workstream tags (AI Visibility Program / Website Conversion Infrastructure /
-- Social Media Management / Operations) are a first-pass categorization by the
-- build agent. Review and correct via PATCH /tasks/{id} if any are miscategorized.
-- on_hold_client statuses were inferred from ClickUp 'Client Actions' list
-- membership, not from an explicit per-task 'awaiting approval' statement.
-- Review these specifically before the first client draft goes out.

INSERT INTO tasks (origin, external_ref, title, status, task_type, cadence, assignee, internal_blocked, blocker_note, workstream) VALUES
  ('tracker', '86d38fuq4', 'Grant backend CMS access to Aithical OR introduce Blue Petal for coordination', 'on_hold_client', 'one_shot', NULL, NULL, false, 'Awaiting Cas/Chris action (ClickUp Client Actions list)', 'Website Conversion Infrastructure'),
  ('tracker', '86d38fupz', 'Send testimonial request to 30 customers (once Aithical provides draft)', 'on_hold_client', 'one_shot', NULL, NULL, false, 'Awaiting Cas/Chris action (ClickUp Client Actions list)', 'Social Media Management'),
  ('tracker', '86d38fupt', 'Confirm Instagram and Facebook login credentials are working', 'on_hold_client', 'one_shot', NULL, NULL, false, 'Awaiting Cas/Chris action (ClickUp Client Actions list)', 'Social Media Management'),
  ('tracker', '86d38fupn', 'Send confirmed store hours for all three locations (LIC + both 28th St.)', 'on_hold_client', 'one_shot', NULL, NULL, false, 'Awaiting Cas/Chris action (ClickUp Client Actions list)', 'Website Conversion Infrastructure'),
  ('tracker', '86d38fuph', 'Decision: approve public product preview layer (Cass to discuss with partners)', 'on_hold_client', 'one_shot', NULL, NULL, false, 'Awaiting Cas/Chris action (ClickUp Client Actions list)', 'AI Visibility Program'),
  ('tracker', '86d38funv', 'Update webshop page title (remove test label, rebrand)', 'to_do', 'one_shot', NULL, 'Tina Ng, Kamil Gul', false, NULL, 'Website Conversion Infrastructure'),
  ('tracker', '86d38funm', 'Add store hours to all location pages', 'completed', 'one_shot', NULL, NULL, false, NULL, 'Website Conversion Infrastructure'),
  ('tracker', '86d38fun9', 'Confirm exact broken page URL from scan (verify before flagging to client)', 'completed', 'one_shot', NULL, NULL, false, NULL, 'Website Conversion Infrastructure'),
  ('tracker', '86d38fun1', 'Create and set up NYFG TikTok account', 'to_do', 'one_shot', NULL, NULL, false, NULL, 'Social Media Management'),
  ('tracker', '86d38fumh', 'Take over YouTube channel management and complete profile setup', 'to_do', 'one_shot', NULL, NULL, false, NULL, 'Social Media Management'),
  ('tracker', '86d38fukm', 'Verify Facebook and Instagram account access is working', 'to_do', 'one_shot', NULL, NULL, false, NULL, 'Social Media Management'),
  ('tracker', '86d38fujn', 'Draft testimonial outreach email for Chris to send to 30 customers', 'completed', 'one_shot', NULL, NULL, false, NULL, 'Social Media Management'),
  ('tracker', '86d38fuhv', 'Draft company background section (two paragraphs: hierarchy + uniqueness)', 'to_do', 'one_shot', NULL, NULL, false, NULL, 'AI Visibility Program'),
  ('tracker', '86d38fuhq', 'Update website title tag with premium wholesale positioning (two options for approval)', 'to_do', 'one_shot', NULL, NULL, false, NULL, 'AI Visibility Program'),
  ('tracker', '86d38fuhk', 'Add metadata and schema labels to website (AI-readable structured data)', 'to_do', 'one_shot', NULL, NULL, false, NULL, 'AI Visibility Program'),
  ('tracker', '86d38fuhb', 'Add phone number to website header', 'to_do', 'one_shot', NULL, NULL, false, NULL, 'Website Conversion Infrastructure'),
  ('tracker', '86d38fuh7', 'Build wholesale account interest form (lead capture funnel)', 'in_progress', 'one_shot', NULL, NULL, false, NULL, 'Website Conversion Infrastructure'),
  ('tracker', '86d38fuh2', 'Set up Google Voice number routing voicemail-to-email for website header', 'in_progress', 'one_shot', NULL, NULL, false, NULL, 'Website Conversion Infrastructure'),
  ('tracker', '86d38fugv', 'Build public product preview layer (ungated webshop facade)', 'completed', 'one_shot', NULL, NULL, false, NULL, 'AI Visibility Program'),
  ('tracker', '86d380mxd', 'Cherry - Follow up with Chris to confirm 1pm NYFG call', 'completed', 'one_shot', NULL, 'Cherry', false, NULL, 'Operations'),
  ('tracker', '86d380mrm', 'Carlo - Join call with Chris re: New York Flower Group', 'completed', 'one_shot', NULL, 'Carlo Duca', false, NULL, 'Operations'),
  ('tracker', '86d380mhx', 'Carlo - Send NY expo lead emails in bulk (pending Jay approval)', 'completed', 'one_shot', NULL, 'Carlo Duca', false, NULL, 'Operations'),
  ('tracker', '86d380mgt', 'Carlo - Review NYFG WhatsApp thread and continue active tasks', 'completed', 'one_shot', NULL, 'Carlo Duca', false, NULL, 'Operations'),
  ('tracker', '86d37kahh', 'Verify web shop logins', 'completed', 'one_shot', NULL, 'Cherry', false, NULL, 'Website Conversion Infrastructure'),
  ('tracker', '86d37kagn', 'Follow up with Chris re: 1pm NYFG call', 'completed', 'one_shot', NULL, 'Cherry', false, NULL, 'Operations'),
  ('tracker', '86d37kafx', 'Review WhatsApp thread and resume NYFG tasks', 'completed', 'one_shot', NULL, 'Carlo Duca', false, NULL, 'Operations'),
  ('tracker', '86d32cc2m', 'Create LinkedIn company page - New York Flower Group', 'to_do', 'one_shot', NULL, 'Tina Ng', false, NULL, 'Social Media Management'),
  ('tracker', '86d32cc29', 'Optimize Google Business Profile - New York Flower Group', 'in_progress', 'one_shot', NULL, 'Tina Ng', false, NULL, 'Social Media Management'),
  ('tracker', '86d30ddyh', 'Cherry to follow up with Chris', 'completed', 'one_shot', NULL, 'Cherry', false, NULL, 'Operations'),
  ('tracker', '86d30995y', 'Upload existing NYFG videos to YouTube channel', 'to_do', 'one_shot', NULL, 'Kamil Gul', false, NULL, 'Social Media Management'),
  ('tracker', '86d30995a', 'Coordinate in-person NYC meeting - May 29 content shoot', 'to_do', 'one_shot', NULL, 'Penny J, Admin', false, NULL, 'Social Media Management'),
  ('tracker', '86d30994t', 'Source micro-influencer targets for unboxing content', 'to_do', 'one_shot', NULL, 'Penny J, Kamil Gul', false, NULL, 'Social Media Management'),
  ('tracker', '86d30994d', 'AI chatbot/FAQ assistant for website', 'to_do', 'one_shot', NULL, 'Tina Ng', false, NULL, 'AI Visibility Program'),
  ('tracker', '86d309944', 'Schedule follow-up meeting - then bi-weekly cadence', 'to_do', 'one_shot', NULL, 'Penny J', false, NULL, 'Operations'),
  ('tracker', '86d30993u', 'Confirm project plan access for Chris and Cass', 'completed', 'one_shot', NULL, 'Admin, Tina Ng, Carlo Duca', false, NULL, 'Operations'),
  ('tracker', '86d30993t', 'Marketing automation - single-publish workflow', 'to_do', 'one_shot', NULL, 'Tina Ng', false, NULL, 'Social Media Management'),
  ('tracker', '86d30993m', 'Social media profile alignment - consistent branding', 'to_do', 'one_shot', NULL, 'Penny J', false, NULL, 'Social Media Management'),
  ('tracker', '86d309934', 'Blog - 3-company merger history for AI knowledge graph', 'to_do', 'one_shot', NULL, 'Tina Ng', false, NULL, 'AI Visibility Program'),
  ('tracker', '86d30992r', 'Website audit fixes - trust badges, testimonials, story', 'in_progress', 'one_shot', NULL, 'Tina Ng', false, NULL, 'Website Conversion Infrastructure'),
  ('tracker', '86d30992d', 'Press coverage - 2+ publications', 'to_do', 'one_shot', NULL, 'Suhas A', false, NULL, 'AI Visibility Program'),
  ('tracker', '86d30991z', 'Directory submissions - Yelp, wholesale directories', 'in_progress', 'one_shot', NULL, 'Penny J', false, NULL, 'AI Visibility Program'),
  ('tracker', '86d30991w', 'GBP full optimization', 'to_do', 'one_shot', NULL, 'Tina Ng, Penny J', false, NULL, 'Social Media Management'),
  ('tracker', '86d30991q', 'Build ungated product showcase page for AI crawlers', 'in_progress', 'one_shot', NULL, 'Tina Ng', false, NULL, 'AI Visibility Program'),
  ('tracker', '86d30991a', 'Create Reddit presence for NYFG', 'in_progress', 'one_shot', NULL, 'Tina Ng', false, NULL, 'Social Media Management'),
  ('tracker', '86d309916', 'Create LinkedIn company page for NYFG', 'completed', 'one_shot', NULL, 'Tina Ng', false, NULL, 'Social Media Management'),
  ('tracker', '86d309911', 'Follow up on GBP ownership transfer', 'completed', 'one_shot', NULL, 'Penny J', false, NULL, 'Social Media Management'),
  ('tracker', '86d30990w', 'Send Chris consolidated access checklist', 'completed', 'one_shot', NULL, 'Admin', false, NULL, 'Operations'),
  ('tracker', '86d30990q', 'Check Met Gala / event photo permissions with Raul Avila', 'on_hold_client', 'one_shot', NULL, NULL, false, 'Awaiting Cas/Chris action (ClickUp Client Actions list)', 'Social Media Management'),
  ('tracker', '86d30990g', 'Discuss webshop ungating feasibility with Blue Petal devs', 'on_hold_client', 'one_shot', NULL, NULL, false, 'Awaiting Cas/Chris action (ClickUp Client Actions list)', 'Website Conversion Infrastructure'),
  ('tracker', '86d30990a', 'Supply existing video content for YouTube upload', 'on_hold_client', 'one_shot', NULL, NULL, false, 'Awaiting Cas/Chris action (ClickUp Client Actions list)', 'Social Media Management'),
  ('tracker', '86d309903', 'Intro call with Blue Petal (Bert) - ungated product page', 'on_hold_client', 'one_shot', NULL, NULL, false, 'Awaiting Cas/Chris action (ClickUp Client Actions list)', 'Website Conversion Infrastructure'),
  ('tracker', '86d3098zq', 'Supply historical press/publication references', 'on_hold_client', 'one_shot', NULL, NULL, false, 'Awaiting Cas/Chris action (ClickUp Client Actions list)', 'AI Visibility Program'),
  ('tracker', '86d3098zk', 'Get 2-3 video testimonials from clients (offer free flowers)', 'on_hold_client', 'one_shot', NULL, NULL, false, 'Awaiting Cas/Chris action (ClickUp Client Actions list)', 'Social Media Management'),
  ('tracker', '86d3098zf', 'Collect 10-20 written testimonials from top clients', 'on_hold_client', 'one_shot', NULL, NULL, false, 'Awaiting Cas/Chris action (ClickUp Client Actions list)', 'Social Media Management'),
  ('tracker', '86d3098z9', 'Designate single email focal point for all platforms', 'on_hold_client', 'one_shot', NULL, NULL, false, 'Awaiting Cas/Chris action (ClickUp Client Actions list)', 'Operations'),
  ('tracker', '86d3098yw', 'Provide website backend access', 'on_hold_client', 'one_shot', NULL, NULL, false, 'Awaiting Cas/Chris action (ClickUp Client Actions list)', 'Website Conversion Infrastructure'),
  ('tracker', '86d3098ye', 'Provide social media logins - Instagram, Facebook, YouTube', 'on_hold_client', 'one_shot', NULL, NULL, false, 'Awaiting Cas/Chris action (ClickUp Client Actions list)', 'Social Media Management'),
  ('tracker', '86d3098xx', 'GBP Access - Transfer ownership from Yordy Doliman', 'on_hold_client', 'one_shot', NULL, NULL, false, 'Awaiting Cas/Chris action (ClickUp Client Actions list)', 'Social Media Management'),
  ('project', NULL, 'Squarespace code injection to embed AI chatbot widget on nyfg.nyc', 'in_progress', 'one_shot', NULL, 'Bert / Blue Petal', false, NULL, 'AI Visibility Program'),
  ('project', NULL, 'Testimonials About page mockup: Claude Design refinement, then Chris/Cas approval', 'in_progress', 'one_shot', NULL, NULL, false, NULL, 'Website Conversion Infrastructure'),
  ('project', NULL, 'Reddit two-step strategy: Week 1 edits for Batch 1, execute Batch 2 posts', 'in_progress', 'one_shot', NULL, NULL, false, NULL, 'Social Media Management');
